site_name: Documentación
repo_url: https://github.com/Rafcrak/documentacion
repo_name: GitHub
nav:
  - Inicio: "index.md"
  - Servicios: "./servicios/index.md"
  - Docker: "./docker/index.md"
  - Kubernetes: "./kubernetes/index.md"
  - Prácticas: "./Civica/index.md"
theme:
  name: mkdocs
  lenguage: es
  locale: es
  include_sidebar: false
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.sections
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Cambiar al modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Cambiar al modo claro
  font:
    code: Source Code Pro
